[package]
name = "sixteen"
version = "0.1.0"
authors = ["Anders Janmyr <anders@janmyr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combinations = "0.1"
